Remove dependencies from `ibc-relayer-types`
informalsystems/hermes-sdk pull request #489
Opened 2024-12-06 13:08 UTC by ljoss17

Closes: #XXX

## Description

This PR removes all dependencies from `ibc-relayer-types`

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2024-12-06 17:07 UTC, soareschen requested changes

2024-12-09 09:46 UTC, ljoss17 commented on crates/cosmos/cosmos-chain-components/src/types/events/channel.rs
> +pub fn try_chan_open_init_from_abci_event(event: &Event) -> Result<Option<OpenInit>, Report> {
Done in 6204eeee4048d00cb9ddb484b1464b6777b19b22 for this file

2024-12-09 09:46 UTC, ljoss17 commented on crates/cosmos/cosmos-chain-components/src/types/events/channel.rs
> +            })?;
Done in 6bf0fdb625e3a4c718e57fa74068dcf9db1155a6

2024-12-09 10:08 UTC, soareschen approved these changes

2024-12-09 10:08 UTC, merged